- Source/Engine.vcxproj
- Source/FileSystem.h
- Source/FileSystem/Importers/Importer.h
- Source/FileSystem/ModuleFileSystem.h
- feat: Implementation of an abstract base class Importer
> Merge Importers with Filesystem

- Source/DataModels/GameObject/GameObject.cpp
- Source/DataModels/GameObject/GameObject.h
Changes in constructor, destructor, Update and CreateComponent
> Merge refactored GameObject Class into SceneManagement

- Source/DataModels/Components/Component.h
- Source/DataModels/Components/ComponentDirLight.cpp
- Source/DataModels/Components/ComponentDirLight.h
- Source/DataModels/Components/ComponentLight.cpp
- Source/DataModels/Components/ComponentLight.h
- Source/DataModels/Components/ComponentPointLight.cpp
- Source/DataModels/Components/ComponentPointLight.h
- Source/DataModels/Components/ComponentSpotLight.cpp
- Source/DataModels/Components/ComponentSpotLight.h
- Source/Engine.vcxproj
- Source/Engine.vcxproj.filters
Added a component <b>ComponentLight</b> which has three subclasses (<b>ComponentDirLight</b>, <b>ComponentPointLight</b> and <b>ComponentSpotLight</b>)
> feat [Lights]: Added directional, point and spot light classes

- Source/DataModels/Components/ComponentLight.h
- Source/Engine.vcxproj
- Source/Engine.vcxproj.filters
Fixed bug with the ComponentLight class due to missing the inline prompt in front of the SetColor and SetIntensity functions
> fix [Lights]: fixed bug due to missing inline declaration

- Source/Application.cpp
- Source/Application.h
- Source/FileSystem/ModuleFileSystem.cpp
- Source/FileSystem/ModuleFileSystem.h
Implementantion of FileSystem Module to load buffer using files.
> Filesystem filesystemmodule

- Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
- Source/DataModels/Windows/EditorWindows/WindowInspector.h
- Source/Engine.vcxproj
- Source/Engine.vcxproj.filters
- Source/Modules/ModuleEditor.cpp
Add the new InspectorWindow to the main SceneManager branch.
> Merge InspectorWindow to SceneManager

- Source/DataModels/Resources/Resource.h
- Source/FileSystem/ModuleResources.cpp
- Source/FileSystem/ModuleResources.h
- Source/Globals.h
ModuleResource File Extension detection on ImportResource();
> Add FileExtension detection to FileSystem resources

- Source/FileSystem/ModuleResources.cpp
- Source/FileSystem/ModuleResources.h
Implementation of a Thread for Import Resource
> Filesystem resourcethread

- Source/DataModels/Resources/Resource.h
- Source/DataModels/Resources/ResourceMesh.cpp
- Source/DataModels/Resources/ResourceMesh.h
- Source/DataModels/Resources/ResourceTexture.cpp
- Source/DataModels/Resources/ResourceTexture.h
- Source/FileSystem/ModuleResources.cpp
GlTexture created in ResourceTexture, Buffer Objects created in ResourceMesh. All Resource members have getter and setter functions.
ModuleResources will copy the original file and save it to the corresponding assets folder
> Methods to initialize resource members + file copied in assets folder

- Source/FileSystem/Importers/Importer.h
- Source/FileSystem/Importers/MeshImporter.cpp
- Source/FileSystem/Importers/MeshImporter.h
- Source/FileSystem/Importers/ModelImporter.cpp
- Source/FileSystem/Importers/ModelImporter.h
- Source/FileSystem/Importers/TextureImporter.cpp
- Source/FileSystem/Importers/TextureImporter.h
- Source/Modules/ModuleRender.cpp
Importer::Save and Importer::Load made protected, aiScene released after importing to avoid memory leaks
> Minor refactors to importers

- Source/DataModels/Windows/EditorWindows/WindowEditorControl.cpp
- Source/DataModels/Windows/EditorWindows/WindowEditorControl.h
- Source/Modules/ModuleScene.cpp
- Source/Modules/ModuleScene.h
Modified the control buttons to be only 2 with Play/Stop function being used on the Play button.  Also stremlined the functions so they do not need any kind of variable for now.
> feat[EditorControl]

- Source/FileSystem/ModuleFileSystem.cpp
- Source/FileSystem/ModuleFileSystem.h
- Source/FileSystem/ModuleResources.cpp
- Source/FileSystem/ModuleResources.h
- Source/Modules/ModuleInput.cpp
Implementation of resources initial importation and thread detached to monitor integrity of files between Assets and Lib
> Filesystem monitor thread physfs

- Source/FileSystem/ModuleFileSystem.cpp
- Source/FileSystem/ModuleFileSystem.h
- Source/FileSystem/ModuleResources.cpp
- Source/Modules/ModuleInput.cpp
Fix problem with filesystem from outside due physfs library
> Filesystem copy outside

- Source/FileSystem/ModuleResources.cpp
- Add 4 s of restime for thred asset monitoring
> Filesystem add restime thread

- Game/Assets/Shaders/default_fragment.glsl
- Source/DataModels/3DModels/Mesh.cpp
- Source/DataModels/3DModels/Model.cpp
- Source/DataModels/3DModels/Model.h
- Source/DataModels/Resources/ResourceMaterial.h
- Source/FileSystem/Importers/ModelImporter.cpp
Distinction between TextMaps and colors & correct shininess implementation
> feat[Fragment]:  maps or colors & shininess

- README.md
- Add explanation for mode game in README.md
> perf: Add explanation for mode game in README.md

- Source/DataModels/Windows/EditorWindows/WindowResources.cpp
- Source/DataModels/Windows/EditorWindows/WindowResources.h
- Source/Engine.vcxproj
- Source/Engine.vcxproj.filters
- Source/FileSystem/ModuleResources.cpp
- Source/FileSystem/ModuleResources.h
- Source/Modules/ModuleEditor.cpp
Allows the user to see all resources and their info, load and unload them and even delete them (along with their files in library).
> feat: resources window

- Source/DataModels/Scene/Scene.cpp
- Source/DataModels/Scene/Scene.h
- Source/DataStructures/Quadtree.cpp
- Source/DataStructures/Quadtree.h
- Source/Modules/ModuleRender.cpp
- Source/Modules/ModuleRender.h
- Source/Modules/ModuleScene.cpp
Applied unique and raw pointers to Quadtree hierarchy, Depending to change GameObjects vectors
> Refactor[Quadtree]: Unique + raw pointers

- .gitignore
- Source/DataModels/Components/ComponentMaterial.cpp
- Source/DataModels/Components/ComponentMeshRenderer.cpp
- Source/DataModels/Program/Program.cpp
- Source/DataModels/Program/Program.h
- Source/DataModels/Scene/Scene.cpp
- Source/DataModels/Skybox/Skybox.cpp
- Source/DataModels/Windows/SubWindows/WindowRenderer.cpp
- Source/DataModels/Windows/SubWindows/WindowRenderer.h
- Source/Modules/ModuleProgram.cpp
- Source/Modules/ModuleProgram.h
- Source/Modules/ModuleRender.cpp
- Source/Modules/ModuleRender.h
With this change is allowed the use of multiples programs shaders.
> Program corrections

- Source/DataModels/Components/ComponentBoundingBoxes.h
- Source/DataModels/Components/ComponentMeshRenderer.cpp
- Source/DataModels/Components/ComponentTransform.cpp
- Source/DataModels/GameObject/GameObject.h
- Source/DataModels/Resources/ResourceSkyBox.cpp
- Source/DataModels/Windows/EditorWindows/WindowFileBrowser.cpp
- Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
- Source/DataStructures/Quadtree.cpp
- Source/Modules/ModuleEngineCamera.cpp
- Source/Modules/ModuleInput.cpp
- Source/Modules/ModuleRender.cpp
- Source/Modules/ModuleRender.h
- Source/Modules/ModuleScene.cpp
> chore: ticket #865bqcbz1

- Source/DataModels/Components/ComponentBoundingBoxes.h
- Source/DataModels/Components/ComponentMeshRenderer.cpp
- Source/DataModels/Components/ComponentTransform.cpp
- Source/DataModels/GameObject/GameObject.cpp
- Source/DataModels/GameObject/GameObject.h
- Source/DataModels/Resources/ResourceSkyBox.cpp
- Source/DataModels/Windows/EditorWindows/WindowFileBrowser.cpp
- Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
- Source/DataStructures/Quadtree.cpp
- Source/Modules/ModuleEngineCamera.cpp
- Source/Modules/ModuleInput.cpp
- Source/Modules/ModuleRender.cpp
- Source/Modules/ModuleRender.h
- Source/Modules/ModuleScene.cpp
In order to approve this pull request, first #145 should have been approved and merged.
> feat: GameObjects can now be moved up and down in the hierarchy

- Source/Modules/ModuleRender.cpp
> fix: disabled GameObject never rendered

- Source/DataModels/GameObject/GameObject.cpp
- Source/DataModels/Scene/Scene.cpp
- Source/DataStructures/Quadtree.cpp
- Source/DataStructures/Quadtree.h
- Source/Globals.h
- Source/Modules/ModuleRender.cpp
- Source/Modules/ModuleScene.cpp
Refactored Quadtree Remove and SmartRemove in order to fix some recursive problems
> fix[Quadtree]: task #865bubdbk

- Source/DataStructures/Quadtree.cpp
- Source/DataStructures/Quadtree.h
- Source/Modules/ModuleRender.cpp
Refactor of quadtree: Here we go again
Please, i only want to finish this. Im gonna be testing all night and if Gerard aprove the merge i will send a message to him to commit the pull
> refactor[Quadtree]: list to setters

- Source/DataModels/GameObject/GameObject.cpp
- Source/DataModels/GameObject/GameObject.h
- Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
- Source/Modules/ModuleEngineCamera.cpp
ClickUp task: https://app.clickup.com/t/865buw83b
> fix [WindowsHierarchy]: task #865buw83b

- README.md
- Source/DataModels/GameObject/GameObject.cpp
- Source/DataModels/Scene/Scene.cpp
- Source/DataModels/Scene/Scene.h
- Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
- Source/DataModels/Windows/SubWindows/WindowFrustum.cpp
- Source/DataStructures/Quadtree.cpp
- Source/DataStructures/Quadtree.h
- Source/Globals.h
- Source/Modules/ModuleEngineCamera.cpp
- Source/Modules/ModuleRender.cpp
- Source/Modules/ModuleScene.cpp
Draft: Save quadtree in JSON format
> feat: quadtree serialization

- Source/DataModels/Components/ComponentTransform.cpp
- Source/DataModels/Components/ComponentTransform.h
Checked all methods returning references to local objects and changed the ones that did. The only ones found are the modified ones.
> Checked all methods returning references to local objects

- Source/DataModels/Windows/SubWindows/ComponentWindows/ComponentWindow.cpp
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentCamera.cpp
Task: https://app.clickup.com/t/865bvrhpg
Issue: #176
> fix: components deletion when not allowed

- Source/Application.cpp
- Source/Application.h
- Source/DataModels/Components/ComponentDirLight.cpp
- Source/DataModels/Components/ComponentPointLight.cpp
- Source/DataModels/Components/ComponentSpotLight.cpp
- Source/DataModels/GameObject/GameObject.cpp
- Source/DataModels/Windows/WindowDebug.cpp
- Source/DataModels/Windows/WindowDebug.h
- Source/Engine.vcxproj
- Source/Engine.vcxproj.filters
- Source/Modules/ModuleDebugDraw.cpp
- Source/Modules/ModuleEditor.cpp
- Source/Modules/ModuleEditor.h
- Source/Modules/ModuleInput.cpp
- Source/Modules/ModuleRender.cpp
Triggered by `Alt+J`. Currently displays light debug stuff, game objects bounding boxes and an ImGui window that does nothing but can be used for showing FPS, disabling/enabling certain options and commands like teleport down the line.
> feat: Game Mode allows debug options

- Source/DataModels/Components/ComponentMaterial.cpp
- Source/DataModels/Components/ComponentMeshRenderer.cpp
- Source/DataModels/Program/Program.cpp
- Source/DataModels/Program/Program.h
- Source/DataModels/Scene/Scene.cpp
- Source/DataModels/Skybox/Skybox.cpp
- Source/DataModels/Windows/SubWindows/WindowRenderer.cpp
- Source/DataModels/Windows/SubWindows/WindowRenderer.h
- Source/Modules/ModuleProgram.cpp
- Source/Modules/ModuleProgram.h
- Source/Modules/ModuleRender.cpp
- Source/Modules/ModuleRender.h
- Source/Shaders/sv.glsl
Modified how the rendering program is managed so that it works as the rest.
> perf: efficient rendering program corrections

- Source/DataModels/Batch/BatchManager.h
- Source/DataModels/Batch/GeometryBatch.cpp
- Source/DataModels/Batch/GeometryBatch.h
- Source/FileSystem/ModuleResources.cpp
- Source/FileSystem/ModuleResources.h
Depends on if we are on ENGINE or GAME the batch deletes the resource once it desapear or stores it in a vector binResource
> feat: delete mesh depending ENGINE mode

- Source/DataModels/GameObject/GameObject.cpp
> Fix: matrix when added child

- Source/DataModels/Windows/EditorWindows/WindowScene.cpp
Now the user can use W, Q and E to change the mode from translation, rotation and scale respectively.
> Qwe hotkeys

- Source/DataModels/GameObject/GameObject.cpp
> Fix[GameObject]: Update transform childs when Add to other GameObject

- Source/DataModels/Camera/Camera.cpp
- Source/DataModels/Camera/Camera.h
- Source/DataModels/Camera/CameraEngine.cpp
- Source/DataStructures/Quadtree.cpp
- Source/DataStructures/Quadtree.h
- Source/Engine.vcxproj
- Source/Engine.vcxproj.filters
- Source/Physics/Physics.cpp
- Source/Physics/Physics.h
This is the same PR as https://github.com/Horizons-Games/Axolotl-Engine/pull/231 with a new small fix. The reason I create a new one is because the other was not merged in time and GitHub merged wrong the new external dependencies and filters. Now I left the file as it is in develop.
> refactor: Raycast moved to Physics class

- Source/Shaders/default_fragment.glsl
Fixed visual bug due to dividing by 0 when tangents are perpendicular
> Fix[Graphics]: fixed perpendicular tangent problems

- Source/DataModels/GameObject/GameObject.cpp
- Change the return state to continue in LoadOptions to don't stop when a type in unknown
(cherry picked from c692db8)
> fix : change the serialization to don't stop

- Source/DataModels/GameObject/GameObject.h
- Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
- Source/DataModels/Windows/EditorWindows/WindowHierarchy.h
> fix: game object can be deleted regardless of children

- Source/DataModels/Components/ComponentSpotLight.h
- Source/DataModels/Scene/Scene.cpp
- Source/Shaders/default_fragment.glsl
Added the padding to avoid the calculation of the offset for each light
> style: add padding to spot light

- .github/workflows/msbuild.yml
See https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
> chore: added event to allow pipeline to be triggered manually

- Source/DataModels/Animation/AnimationController.cpp
- Source/DataModels/Animation/AnimationController.h
- Source/DataModels/Components/ComponentAnimation.cpp
- Source/DataModels/Components/ComponentAnimation.h
- Source/DataModels/Components/ComponentTransform.cpp
- Source/DataModels/GameObject/GameObject.cpp
- Source/DataModels/GameObject/GameObject.h
- Source/DataModels/Resources/ResourceAnimation.h
- Source/DataModels/Resources/ResourceModel.h
- Source/DataModels/Scene/Scene.cpp
- Source/Engine.vcxproj
- Source/Engine.vcxproj.filters
- Source/FileSystem/Importers/AnimationImporter.h
- Source/FileSystem/Importers/ModelImporter.cpp
- Source/Modules/ModuleScene.cpp
* Now when the controller is on play state the transformations of the first Animation are applied to the bones of the Model.
* Fixed AnimationImportaion problems with the position and rotations
<b>TODO: When David's implementation for the OnPlay/OnStop modes for Application is merged we need to adapt the controller to play the animations or stop playing them relative to the Application's OnPlay/OnStop.</b>
> feat: Engine/animation controller animation

- Source/Physics/Physics.cpp
- Source/Physics/Physics.h
Problem was with #274 and now issue #285 is solved.
> fix: Dynamic Objects selectable

- Source/Engine.vcxproj.user
> fix: Basic .user file added back

- Source/DataModels/Components/ComponentMeshCollider.cpp
- Source/DataModels/Components/ComponentMeshCollider.h
- Source/Modules/ModulePlayer.cpp
- Source/Physics/Physics.cpp
- Source/Physics/Physics.h
New raycast funtion: now you can do an optimal raycast that will return if collides or no, with no more info
> feat[Physics]: new Raycast

- Source/Modules/ModuleUI.cpp
> fix: UI elements actually drawn

- Game/Assets/Scenes/EnemyMovementTrial.axolotl
- Game/Scripts/EnemyCollidesFloorScript.cpp
- Game/Scripts/PatrolBehaviourScript.cpp
- Game/Scripts/SeekBehaviourScript.cpp
- Source/DataModels/Components/ComponentRigidBody.cpp
- Source/Physics/Physics.cpp
Expanded raycast for hierarchies and fixed issues with epsilon values on Quat rotation
> fix: raycast + rotations

- Source/Application.cpp
* Fixed the frame time not being accurate relatively to the frame cap
* Massive boost in performance
> perf[frame_cap]: fixed frame cap not working accurately

- Source/DataModels/Scene/Scene.cpp
I worked really hard in solve the deleter, pls accept as soon as posible
> fix: solve deleter

- Source/DataModels/GameObject/GameObject.cpp
- Source/DataModels/GameObject/GameObject.h
- Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
- Source/DataModels/Windows/EditorWindows/WindowHierarchy.h
Branched from #334, so that must be merged first.
> fix: can move object up and down, corrected use of iterators

- Game/Assets/Scenes/CantinaScriptsVS2.axolotl
- Source/DataModels/Components/ComponentRigidBody.cpp
I saw that the RigidBody component didn't save the gravity value, so the changes were lost.
I have checked the rest of components too and this was the only thing.
> Fix: Rigid body serialization

- Source/DataModels/Scene/Scene.cpp
I found duplicated imports in scene.cpp, idk if there are more in other files
> refactor: delete imports duplicated

- Game/Shaders/default_fragment.glsl
I've added alpha discard to be able to have grids and stuff per texture. The art department requested it asap.
So here it is
> Feat: Alpha discard

- Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowImportScene.cpp
- Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowLoadScene.cpp
- Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowSaveScene.cpp
- Source/DataModels/Windows/WindowMainMenu.cpp
- Source/Modules/ModuleScene.cpp
- Source/Modules/ModuleScene.h
This PR is to centralize in one function the Save Scene code and the Load Scene code. 
Also solved a problem with on the OnPlay and the ImportScene because the code wasn't updated with the last changes on the scene, like the CubeMap or the disappearance of the ambient light. I hope that using all the same functions does not happen again
> Fix: Join Save/Load Scene functions

- Source/Modules/ModuleRender.cpp
Use an NVIDIA function to force it to select the best graphics card available in the system
> feat: always use best graphics card

- Source/DataModels/Components/UI/ComponentButton.cpp
- Source/DataModels/Components/UI/ComponentButton.h
- Source/Modules/ModuleUI.cpp
- Source/Modules/ModuleUI.h
- Disable gameObjects put the hover and clicked booleans to false of any Component Button on that gameObject or children gameObject.
- Check Disable/Enable when check Interaction between mouse and Buttons
> fix: Detect disabled Interaction UI element

- Source/Modules/ModuleInput.cpp
> fix[ModuleInput]: check sdl repeat key state

- Game/Assets/Scenes/Lights_1.axolotl
Reuploaded cause some waste data pushed in the other branch
> feat: Light in scene

- Source/DataModels/GameObject/GameObject.inl
> fix: corrected return condition

- Source/Modules/ModuleRender.cpp
> fix: don't draw if mesh is disabled

- Source/Modules/ModuleRender.cpp
> fix: old getComponent

- Source/Shaders/default_fragment.glsl
- Source/Shaders/specular_fragment.glsl
* Using diffuse alpha when there's a diffuse map
> Graphics/shaders fix  - using diffuse alpha

- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.h
IMPORTANT: the current code assumes the path to all scripts is `Game/Scripts/{scriptName}`. Let me know if you want to be able to use sub folders, in which case more checks would be necessary.
> feat: double click on script window to open it

- Source/DataModels/Components/ComponentAreaLight.cpp
- Source/DataModels/Components/ComponentPointLight.cpp
- Source/DataModels/Components/ComponentSpotLight.cpp
- Source/Shaders/Common/Functions/pbr_functions.glsl
- Source/Shaders/default_fragment.glsl
- Source/Shaders/specular_fragment.glsl
Fixed selected light being drawn (dd) in playmode and fixed minor bug with extreme low values for roughness
> fix[area lights]: Fixed selected light being drawn (dd) in playmode

- Source/DataModels/Components/ComponentScript.cpp
- Source/DataModels/Components/ComponentScript.h
> style[ComponentScript]: fix typo

- Source/DataModels/Components/ComponentAreaLight.cpp
- Source/DataModels/Components/ComponentPointLight.cpp
- Source/DataModels/Components/ComponentSpotLight.cpp
> fix: debugdraw spots and points

- Game/Assets/Scenes/00_LoseScene_VS3.axolotl
- Game/Assets/Scenes/00_MainMenu_V02.axolotl
- Game/Assets/Scenes/00_MainMenu_VS3.axolotl
- Game/Assets/Scenes/00_WinScene_VS3.axolotl
- Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
- Game/Assets/Scenes/Template_HUD-IngameMenu_V03.axolotl
- Game/Assets/Scenes/Test_lights_movement.axolotl
- Source/Application.cpp
- Source/DataModels/Components/ComponentPlayer.cpp
- Source/DataModels/Components/ComponentPlayer.h
- Source/DataModels/Scene/Scene.cpp
- Source/DataModels/Scene/Scene.h
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentPlayer.cpp
- Source/Modules/ModulePlayer.cpp
- Source/Modules/ModulePlayer.h
- Added in component Player a checkbox to select this player as the actualPlayer (The system use the last componentPlayer checked)
- Reworked part of the ModulePlayer player system to use the saved player
- Update scenes with new parameter
- Fix UI scenes
(And we can probably use this in the future to switch to the second player)
> Fix: Actual Player

- Game/Scripts/EnemyDeathScript.cpp
- Game/Scripts/HealthSystem.cpp
> Chore: Erase debugging code

- Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
- Game/Scripts/PlayerManagerScript.cpp
- Game/Scripts/PlayerManagerScript.h
- Game/Scripts/PlayerMoveScript.cpp
- Game/Scripts/PlayerMoveScript.h
Now the rotation with the WASD is smoother
> feat: Continuous rotation with Player

- Game/Scripts/PlayerForceUseScript.cpp
> fix: force animation not finishing when using the force against no objective

- Game/Assets/Cubemaps/sunsetSkybox.cube.meta
- Game/Assets/Textures/SunsetSkyboxHDR.hdr.meta
- Game/Scripts/DefaultScript.cpp
- Game/Scripts/DefaultScript.h
- Source/Auxiliar/Reflection/VectorField.h
- Source/DataModels/Components/ComponentScript.cpp
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.h
- Source/Engine.vcxproj
- Source/Engine.vcxproj.filters
- Source/Enums/FieldType.h
- Source/Scripting/IScript.h
- Source/Scripting/RegisterFieldMacros.h
- Source/VectorField.h
Implemented the vectors and it's serialization in scripting:
-Vector Float
-Vector String
-Vector Bool
-Vector GO
-Vector Float3
(the vector can have as many components as the user defines on the script)
(there is an example in DefaultScript)
> feat: add Vector fields to scripts

- External/ImGui/imgui_bezier.cpp
Clamp the grabbers from Bezier to don't go outside of the window of it
> refactor : clamp the Bezier window

- Source/DataModels/GameObject/GameObject.h
- Source/DataModels/GameObject/GameObject.inl
should avoid many try...catch blocks
> feat: HasComponent method

- Source/Modules/ModuleRender.cpp
As mentioned in discord i have attenuated the bloom error, increased the samplers and fixed one problem with the ping pong buffer
> fix: bloom appears on the left border

- Source/DataModels/Windows/EditorWindows/WindowConsole.cpp
> fix[WindowConsole]: correctly get number of lines to draw

- Game/Scripts/PlayerMoveScript.cpp
Diagonal dash has now a similar force than other directions.
We are still facing the issue that the player does not animate when walking after a dash, but it's a previous bug, so don't consider this problem for approving the current PR
> fix[WIP]: diagonal dash

- Game/Scripts/BixAttackScript.cpp
- Game/Scripts/PlayerJumpScript.cpp
Each commit is self explanatory about what this pr fixes.
> fix: jump attack transition

- Source/Modules/ModuleRender.cpp
correct the bug when the bloom appears in the left side. Also meshes with transparency works again
> fix: bloom

- Source/DataModels/Components/ComponentAreaLight.cpp
- Source/DataModels/Components/ComponentLight.cpp
- Source/DataModels/Components/ComponentLight.h
- Source/DataModels/Components/ComponentPointLight.cpp
- Source/DataModels/Components/ComponentSpotLight.cpp
- Source/DataModels/Scene/Scene.cpp
> Fix: lights when deleting

- Source/DataModels/Components/ComponentAnimation.cpp
- Source/DataModels/Components/ComponentAnimation.h
- Source/DataModels/Components/ComponentRigidBody.cpp
- Source/DataModels/Components/ComponentRigidBody.h
- Source/DataModels/Components/ComponentScript.cpp
Will also try to add fixes to other reported issues once I manage to reproduce them.
> fix: various fixes to copy constructors

- Source/FileSystem/Importers/NavMeshImporter.cpp
- Source/Modules/ModuleEditor.cpp
- Source/Modules/ModuleNavigation.cpp
Seems like the Nav Mesh importer and the Navigation Module were broken when they were added.
> fix: nav mesh importer works

- Game/Scripts/RangedFastAttackBehaviourScript.cpp
- Source/DataModels/Components/ComponentScript.cpp
- Source/DataModels/Components/ComponentScript.h
- Source/Scripting/IScript.h
- Source/Scripting/Script.cpp
- Source/Scripting/Script.h
Implementation of the behaviour to change characters exposed the lack of this feature.
> feat[IScript]: allow access to container ComponentScript

- Game/Scripts/BossChargeAttackScript.cpp
- Game/Scripts/BossMissilesAttackScript.cpp
- Game/Scripts/BossShieldAttackScript.cpp
- Game/Scripts/BossShieldAttackScript.h
- Game/Scripts/EnemyClass.cpp
- Game/Scripts/EnemyDeathScript.cpp
- Game/Scripts/EnemyDroneScript.cpp
- Game/Scripts/EnemyVenomiteScript.cpp
- Game/Scripts/FinalBossScript.cpp
- Game/Scripts/FinalBossScript.h
- Game/Scripts/PlayerForceUseScript.cpp
Before going on holidays, Gerard left me some comments in the boss pr (#662) which I couldn't address because I was out, so the objective of this pr is to address and apply the required changes.
P.S. You can see the discussion and the requested changes [here](https://github.com/Horizons-Games/Axolotl-Engine/pull/662#pullrequestreview-1596513076).
> perf/refactor: final boss code improvements

- Game/Scripts/ElevatorCore.cpp
- Game/Scripts/HackZoneScript.cpp
- Game/Scripts/JumpFinisherArea.cpp
- Game/Scripts/PlayerAttackScript.cpp
- Game/Scripts/PlayerHackingUseScript.cpp
- Source/DataModels/Batch/GeometryBatch.cpp
- Source/DataModels/GameObject/GameObject.cpp
- Source/DataModels/Render/Shadows.cpp
- Source/DataModels/Resources/ResourceNavMesh.cpp
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentAreaLight.cpp
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMeshRenderer.cpp
- Source/DataModels/Windows/SubWindows/WindowFrustum.cpp
- Source/FileSystem/Importers/NavMeshImporter.cpp
- Source/Modules/ModuleRender.cpp
- Source/Modules/ModuleUI.cpp
Self explanatory, after being trying the game, noticed that there were some warnings and some TODOs that were wrong, so I decided to fix them.
> chore: Clear warnings and adapt TODOs

- Game/Scripts/HealthSystem.cpp
- Game/Scripts/PlayerHackingUseScript.cpp
- Source/Modules/ModuleInput.cpp
- Source/Modules/ModuleInput.h
Add a rumble method inside moduleInput that allows control for left and right rumble and duration.
Add rumble on damage taken and on hacking mistake
> feat: rumble

- Game/Assets/Scenes/Gameplay_FinalBoss.axolotl
- Game/Assets/Scenes/Gameplay_TrialBix.axolotl
- Source/DataModels/Components/ComponentLine.cpp
> Fix load component line

- Source/Application.cpp
- Source/Application.h
- Source/DataModels/Schedulable/Schedulable.cpp
- Source/DataModels/Schedulable/Schedulable.h
- Source/Engine.vcxproj
- Source/Engine.vcxproj.filters
- Source/Scheduler.cpp
- Source/Scheduler.h
This cherrypicks the changes in #760 and merges the fix from #765. Felt like the Scheduler was carrying too much responsability, so moved most of it to a proper Schedulable class instead of having a `using` declaration.
> feat: proper Schedulable class

- Source/DataModels/Render/Shadows.cpp
- Source/DataModels/Render/Shadows.h
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLine.h
- Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTrail.h
- Source/Modules/ModulePlayer.cpp
- Source/Modules/ModulePlayer.h
Some of these might be fixed in branches but just in case.
> fix: address all compilation warnings

- Source/Application.h
> fix: use the correct preprocessor definition in Application::GetPlayState

- Source/Modules/ModulePhysics.cpp
Improved the criteria for discarding rigidbodies before the contact test.
Big FPS improvement.
> perf: Collision detection improved

- Game/Scripts/UIHackingManager.cpp
Allow hacking in the last computer of level 1. This has to be merged to develop after the merge of the last release into develop. Pointing to Release 10-10 branch is provisional
> feat: level 1 hacking UI

- Game/Scripts/ActivationLogic.cpp
- Game/Scripts/ActivationLogic.h
[https://discord.com/channels/1029122111832338563/1161526797507244042/1161605863279173783](url)
> fix: Doors doesn't work properly when you finish combat inside the trigger

- Source/DataModels/Windows/SubWindows/WindowFrustum.cpp
- Source/Modules/ModuleDebugDraw.cpp
- Source/Modules/ModuleDebugDraw.h
This moment is important for everybody, now you can make the grid disapear
> Finally no Grid

- Game/Scripts/UIOptionsMenu.cpp
- Source/Modules/ModuleUI.cpp
DPAD controls added for vertical direction in all the menus
> feat: Options gamepad controls (DPAD)

- Game/Scripts/UIOptionsMenu.cpp
- Game/Scripts/UIOptionsMenu.h
Improved readability in UI Options
> refactor: UI options

- Game/Scripts/BossChargeAttackScript.cpp
- Game/Scripts/BossChargeRockScript.cpp
- Source/DataModels/Components/ComponentObstacle.cpp
- Source/DataModels/Components/ComponentObstacle.h
- Source/Modules/ModuleNavigation.cpp
Now the Obstacle should be working correctly, so the boss shouldnt get stuck with them
> Fix: Changes in obstacles logic

- Game/Scripts/ActivationLogic.cpp
- Game/Scripts/CameraControllerScript.cpp
- Game/Scripts/CameraControllerScript.h
- Game/Scripts/CombatTutorial.cpp
- Game/Scripts/CombatZoneScript.cpp
- Game/Scripts/CombatZoneScript.h
- Game/Scripts/ComboManager.cpp
- Game/Scripts/ElevatorCore.cpp
- Game/Scripts/EnemyDeathScript.cpp
- Game/Scripts/EnemyMiniBossTwo.cpp
- Game/Scripts/UIComboManager.cpp
- Source/DataModels/Scene/Scene.cpp
- Source/DataModels/Scene/Scene.h
- Source/Modules/ModulePlayer.cpp
- Source/Modules/ModulePlayer.h
Reworked the system that makes you detect if you are in combat, this fix some interactions and add new things:
- now in miniboss level2 only have the bar when you go down the arena
- Now is easy to acces to combat system
> Rework In Combat System

- Source/DataModels/Windows/EditorWindows/WindowStateMachineEditor.cpp
WindowStateMachine was not updating correctly when new parameter
> fix: Update on new Parameter

- Game/Scripts/CameraBossControllerScript.cpp
- Game/Scripts/CameraBossControllerScript.h
Fixed camera multipliers not working.
> fix: multipliers camera boss

- Game/Scripts/BossShieldAttackScript.cpp
- Game/Scripts/BossShieldAttackScript.h
- Game/Scripts/EnemyMiniBossTwo.cpp
> fix: miniboss 2 freeze

- Game/Scripts/CombatTutorial.cpp
- Game/Scripts/CombatTutorial.h
- Game/Scripts/HealthSystem.cpp
- Game/Scripts/HealthSystem.h
- Game/Scripts/TutorialSystem.cpp
Added some code to take care of the potential death of the dummy before doing the required attacks for the tutorial.
> fix[Combat Tutorial]

- Game/Scripts/CombatTutorial.cpp
- Game/Scripts/CombatTutorial.h
Added new state so the player can take his time learning about power ups, also refactored the update to use switch instead of ifs.
> fix&refactor: powerup tutorial

- Game/Scripts/BossChargeRockScript.cpp
- Game/Scripts/CombatTutorial.cpp
- Game/Scripts/MeshEffect.cpp
- Game/Scripts/SceneLoadingScript.cpp
- Game/Scripts/SceneLoadingScript.h
- Game/Scripts/TutorialSystem.cpp
- Game/Scripts/TutorialSystem.h
- Source/Modules/ModulePlayer.cpp
> feat: allow different loading screens

- Source/DataModels/Batch/GeometryBatch.cpp
- Source/DataModels/Components/ComponentAgent.cpp
- Source/DataModels/Components/ComponentLine.cpp
- Source/DataModels/Components/ComponentObstacle.cpp
- Source/DataModels/Components/ComponentParticleSystem.cpp
- Source/DataModels/Components/ComponentPlanarReflection.cpp
- Source/DataModels/Components/ComponentTrail.cpp
- Source/DataModels/Render/Shadows.cpp
- Source/DataModels/Scene/Scene.cpp
- Source/Modules/ModuleRender.cpp
- Source/Modules/ModuleUI.cpp
Noticed unhanded ComponentNotFoundExceptions.
> fix: in Engine code, use GetComponentInternal
