Horizons-Games/Axolotl-Engine

Source/DataModels/GameObject/GameObject.cpp
Fixed bug where lights would still being rendered after its object parent would be removed, due to the bindings to the shader not being updated
=> fix [lights]: Updated light bindings to fragment shader after delete

Source/DataModels/Components/ComponentMaterial.cpp, Source/DataModels/Components/ComponentTransform.cpp, Source/DataStructures/Quadtree.cpp
Fixed Quadtree, ComponentTransform and removed unnecessary unload in destructor of ComponentMaterial (that for some reason caused a crash, probably because they are deleted after ModuleResources)
=> fix: can load scene

Source/Modules/ModuleEngineCamera.cpp
We missed this when we developed the mouse picking, fixed now!
KeyState::DOWN is only true in the first frame that the left click was pressed, the next frames it will be KeyState::REPEAT, so the ray is only thrown when clicking in the Scene, and not when keeping the left click pressed.
=> fix: Throw raycast just when the mouse is pressed

Source/DataModels/GameObject/GameObject.h, Source/DataModels/Scene/Scene.cpp, Source/DataModels/Scene/Scene.h, Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp, Source/Modules/ModuleRender.cpp, Source/Modules/ModuleScene.cpp
When creating the scene all gameobjects go to vector sceneCamera provoking that when we search for objects inside camera we take those objects as cameras.
#172 must be approved in order to try this changes out correctly.
=> fix: problems deleting gameobjects with children 

Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentSpotLight.cpp
Clickup task: https://app.clickup.com/t/865bk5axr
Capped the maximum angle for the spotlights to 90 degrees. There wasn't actually anything to fix in this case, when the angle for the spotlights was greater than 90 degrees (1.57 radians), the effect that seemed to bug out the light was actually the light bending into itself (?) 'cause the angle was greater than 90 degrees, causing the light to shadow itself (like the effect of a black whole curving light around it in its event horizon).
Other than capping the light, i've changed the imgui to show the values in degrees instead of radians, so it's more clear the angle that is being used for the light.
=> fix [lights]: "fixed" spotlight angle

Source/DataModels/Windows/EditorWindows/WindowScene.cpp
Solved the problem where transformations where not propertly being applied when modifying the objects with the guizmo
=> fix: Guizmo transformations not being applied since last changes in develop

Source/DataStructures/Quadtree.cpp, Source/DataStructures/Quadtree.h
Fix an design error where and object outside of the quadtree but with a part inside didn't make the main quadtree to expand
=> fix[QuadTree]: Expansion

Source/DataModels/Camera/Camera.cpp, Source/DataModels/Camera/Camera.h, Source/DataModels/Camera/CameraEngine.cpp, Source/DataModels/Camera/CameraEngine.h, Source/DataModels/Camera/CameraGameObject.cpp, Source/Modules/ModulePlayer.cpp
Now that the Camera refactor is finally done, I solved this bug which appeared during the Concept Discovery.
- The problem was that the Focus stops at the frame when the final rotation is achieved. This has been aligned also with position and its Lerp.
- I modified the Slerp algorithm for not needing the current rotation and only use the current front direction.
- The speed has been adjusted too.
=> fix: Camera Focus movement and rotation not aligned

Source/DataModels/Resources/Resource.h, Source/DataModels/Resources/ResourceMaterial.cpp, Source/DataModels/Resources/ResourceMaterial.h, Source/DataModels/Resources/ResourceMesh.h, Source/DataModels/Resources/ResourceModel.h, Source/DataModels/Resources/ResourceSkyBox.h, Source/DataModels/Resources/ResourceTexture.cpp, Source/DataModels/Resources/ResourceTexture.h, Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowTextureInput.cpp, Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowTextureInput.h, Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMaterial.cpp, Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMaterial.h, Source/FileSystem/Importers/MaterialImporter.cpp, Source/FileSystem/Importers/TextureImporter.cpp, Source/FileSystem/ModuleResources.cpp
This solves some problems that occurred in the modification of the material. When you modified a material, the changes were only saved in case of changing a texture, not when we modified other parameters such as smoothness.
Another problem is that the load options in modifiable resources (Like material) had problems when reimporting because information that was only in the binary was lost. That's why now in engine mode load options are imported from the .meta to avoid these problems and in game mode from the binary as it should be.
To avoid having to reimport binary all the time, I add a Apply changes button, just like the one for the texture load/import options, but to ComponentMaterial.
=> Feat: Material load/save options

Source/DataModels/Scene/Scene.cpp
This is a fast patch, I'll check it better later.
When you drag and drop 4 different fbx the first one disappears.
For some reason when you load a model, mesh and material, then unload them and THEN load the mesh and material again. This problem appears. It doesn't make any sense because it should be fine, but I deleted the first Load because it was repetitive and patch the problem temporaly for the Level Design Team.
=> Fix: Erase double Load of Mesh/Component

Source/FileSystem/ModuleResources.cpp
(cherry picked from commit d0c1f90548cb19119caf87d6b103c56051309802)
=> fix: resources imported from assets folder instead of original path

Source/DataModels/Scene/Scene.cpp
When you create or assign data to a ssbo is not necessary to use any program. They are stored in globally so any shader can use them.
=> perf[Lights]: delete program where is not necessary

Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp, Source/FileSystem/Importers/ModelImporter.cpp
Removed the drawing of the extra nodes that assimp creates when importing models, with the information of the pre_rotations and pre_translations applied to the bones (this commit only affects the imgui drawing of the hirearchy, we must keep the nodes themselves for the animations)
<b>Before</b>             |  <b>After</b>
:-------------------------:|:-------------------------:
=> refactor[Engine/animation]: remove extra nodes from hierarchy

Source/DataModels/Components/ComponentMockState.cpp, Source/DataModels/Components/ComponentMockState.h, Source/DataModels/Windows/EditorWindows/WindowInspector.cpp, Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMockStates.cpp
Looking at it with Rubén, turns out the error was caused because we didn't reserve enough memory for the buffer, so whenever we added a character it got relocated to another memory address, which ended up causing that weird glitch. The reason it worked after 17 characters where added was because at that point the memory reserved 32 bytes (after doubling from 16), which is less than the 24 bytes of the buffer.
=> fix: fixed weird error remaining from #242

.github/workflows/msbuild.yml
Cherrypick of #276. According to the docs (linked in the original MR), the file needs to be in the default branch of the repository in order for the changes to take effect.
=> chore[main]: allow manual pipeline

Source/DataModels/Resources/ResourceSkyBox.cpp
I added the elimination of vao and vbo and move LoadVBO, createVAO and textureParameters outside the loop
=> fix[SkyBox]: delete buffers correctly && move createVBO and VAO

Source/DataModels/Windows/EditorWindows/EditorWindow.h, Source/DataModels/Windows/EditorWindows/WindowConfiguration.h, Source/Modules/ModuleEditor.cpp
Also allowed each window to define whether it should be opened or closed by default.
=> fix: avoid crash if WindowStates.conf doesn't match the actual windows in ModuleEditor

Source/DataModels/GameObject/GameObject.cpp, Source/DataModels/GameObject/GameObject.h, Source/DataModels/Scene/Scene.cpp, Source/Engine.vcxproj
This will make it so not capturing the return value of `GameObject::UnlinkChild` will result in a compiler error. This will ideally force everyone to be aware that this function gives ownership of the pointer and avoid memory leaks, which there was already one.
Relevant documentation:
https://en.cppreference.com/w/cpp/language/attributes/nodiscard
=> chore/fix: GameObject::UnlinkChild has [[nodiscard]] tag

Source/FileSystem/Importers/MaterialImporter.cpp, Source/Modules/ModuleScene.cpp
Textures were not appearing correctly in game mode because the UIDs of the materials were not correctly passed from Save to Load functions in the binaries. Load and save methods are now working propertly for these materials.
=> fix: material in game mode

Source/DataModels/Scene/Scene.cpp
After calling `std::remove_if`, you must call `erase` using the iterator it returns. Someone didn't read the full documentation ^^'
=> fix: corrected use of remove_if

Source/FileSystem/Importers/MaterialImporter.cpp
Fix bug #347 
In GameMode we don't have the asset folder, so we can't acces the metas and need to save the load options (The importer options aren't necessary) in the binary for that purpose. This was made for all the editable options on Material on VS1.
I Updated the Material binary to save smoothness and metalness, it was forgotten in the latest Material refactor.
=> Fix: Add Metalness and Smothness on GameMode

Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
Not improved in a performance way, but in a visual way:
- The reset script button has been changed to a remove button.
- The list of scripts is not shown if a script is already loaded.
- Fixed a couple warnings (C-style casts and const variables)
=> feat: Remove/Load new scripts from the graphical interface improved

Source/DataModels/Components/ComponentRigidBody.cpp, Source/DataModels/Components/ComponentRigidBody.h
- When you have a RigidBody and you disable the component, the collider keeps moving even if the mesh do the expected behaviour
=> Fix: rigid body enable

Source/Modules/ModuleUI.cpp, Source/Modules/ModuleUI.h
- UI draw hierarchy recursively
- Fix Enable bug: UI only check the canvas enable not the rest of the gameObjects, and ignore the Component enable.
=> fix: UI Draw Hierarchy Recursive

Source/DataStructures/Quadtree.cpp, Source/Globals.h
This was the bug that was making infinite loop if height was superior to minquadrant size (this bug was since start but we didn't notice)
=> fix: diagonal solved

Source/DataModels/Scene/Scene.cpp, Source/DataModels/Scene/Scene.h, Source/Modules/ModuleScene.cpp
As mentioned in the code, the method to remove the GameObject that is being deleted from the scripts turned out relatively complex. Tried my best to explain what it's doing with comments.
=> fix/refactor: delay adding updatables to scene, deleting objects. GameObjects removed from scripts that reference them

Source/DataModels/Windows/PopUpWindows/WindowBuild.cpp
Basically disables the checkbox if the zip is not found. Necessary because not only you need one to run the game, the startup configuration also expects one, so we run into the risk of getting an error. Also added a tooltip to let the user know why the checkbox is disabled.
=> feat: if no zip file exists, force user to create it

Source/DataModels/Camera/Camera.cpp, Source/Modules/ModuleInput.h
Small QOL, we are able to replace calls like
```c++
input->GetKey(SDL_SCANCODE_UP)
```
for
```c++
(*input)[SDL_SCANCODE_UP]
```
Important to de-reference the pointer, otherwise we'd be calling the operator overload for pointer types, instead of the one in `ModuleInput`.
`GetKey` remains untouched, so this doesn't require any updates to pre-existing code.
=> feat: overload array subscript operator in ModuleInput

Game/Scripts/PlayerDeathScript.cpp
Now all the scripts that Bix has get disabled upon death except the one in charge of loading the death screen.
=> fix: stop Bix movement and allow for the death screen to load

Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl, Game/Scripts/BixAttackScript.cpp, Game/Scripts/BixAttackScript.h, Game/Scripts/EntityDetection.cpp, Game/Scripts/EntityDetection.h, Source/Engine.vcxproj, Source/Engine.vcxproj.filters
Entity detection is in charge of detecting which enemy is in front of the player in order to perform attacks to them.
It consists on a sphere detecting all enemies near the player and an angle detecting which of them are in front of the player. The enemy selected will be, for the moment, the nearest to the player inside this angle. For now, the player only hits one enemy at the time.
I've also linked this script with the BixAttack script in order to hit the enemy selected.
To test this you can go to the GameplayFullTrial_VS3.axolotl
=> Feat: Entity Detection and linked with Bix Attack

Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp, Source/DataModels/Windows/EditorWindows/WindowHierarchy.h
- Filter game objects in the hierarchy, only draw those which's names contain the string written by the user.
- Filter is only set up when the search bar text changes, so we don't iterate the whole hierarchy each frame. When filter is set up, hierarchy is only traversed once (cost should be N).
- Use `unordered_set`, which according to the internet, is the most efficient container to use for searches.
=> feat: add search bar to WindowHierarchy

Source/Modules/ModuleScene.cpp
Quick fix because otherwise windows with certain dependencies explode when loading.
=> fix: RefreshInspector before load

Game/Scripts/CameraControllerScript.cpp, Source/DataModels/Components/ComponentCameraSample.cpp, Source/DataModels/Components/ComponentCameraSample.h, Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentCameraSample.cpp
New combat sample points option:
- A Combat Point will be prioritized over general samples. The order now is the following:
1. Closest point of Combat Points
2. Combat Point with influence 
3. Closest point of General Sample Points
4. General Sample Point with influence
- Different color for distinguish both types
- For enabling Combat Point only tick the checkbox
- For QoL, if you select the parent samples object, all the children will be drawn. If not, only the ones selected will be drawn.
=> feat: Combat camera

Source/DataModels/Batch/GeometryBatch.cpp, Source/DataModels/Batch/GeometryBatch.h, Source/DataModels/Resources/ResourceMaterial.cpp, Source/DataModels/Resources/ResourceMaterial.h, Source/DataModels/Scene/Scene.cpp, Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMeshRenderer.cpp, Source/Shaders/color_correction_fragment.glsl, Source/Shaders/gBuffer_Metallic_fs.glsl, Source/Shaders/gBuffer_Specular_fs.glsl
As mentioned during wednesday's meeting i added a drag to manipulate the bloom intensity of each material, you can find it below the emissive texture. I have limited the value  between 0.05 and 1. For test it you can use the level 1. Remember that with F1 you can disable the bloom.
=> feat: bloom modificable for each material

Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMeshRenderer.cpp
As per `ImGui::BeginChild` documentation (skipping to the relevant part):
> For each independent axis of 'size': ==0.0f: use remaining host window size / >0.0f: fixed size / <0.0f: use remaining window size minus abs(size) / Each axis can use a different mode, e.g. ImVec2(0,400).
Looks like this was the reason the window took the remaining space of the parent window.
=> fix[WindowComponentMeshRenderer]: remove call to BeginChild

Game/Scripts/BixAttackScript.cpp, Game/Scripts/BixAttackScript.h, Game/Scripts/PlayerMoveScript.cpp, Game/Scripts/PlayerMoveScript.h
Hi! I made this changes because I felt that the attack was a little bit off. I made it without consulting so please, any change or suggestion is welcomed.
This PR makes the character look at the enemy targeted while attacking. Also, slows down the velocity movement while attacking, that's to gain more control of the character and because it felt weird moving the character while the attack animation was still.
=> Feat: Attack Movement Improvement

Source/DataModels/GameObject/GameObject.h, Source/DataModels/GameObject/GameObject.inl
This also allows `HasComponent` to work with scripts.
Info regarding SFINAE (Substitution Failure Is Not An Error): https://en.cppreference.com/w/cpp/language/sfinae
=> refactor[GameObject]: use concepts instead of SFINAE for component methods

Source/DataModels/Components/ComponentPlayer.cpp, Source/DataModels/Components/ComponentPlayer.h, Source/DataModels/Components/ComponentRigidBody.cpp, Source/DataModels/GameObject/GameObject.cpp, Source/DataModels/Scene/Scene.cpp, Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentAreaLight.cpp, Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMeshRenderer.cpp, Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentParticle.cpp, Source/DataModels/Windows/SubWindows/WindowFrustum.cpp, Source/Defines/AxoTodo.h, Source/Engine.vcxproj, Source/Engine.vcxproj.filters, Source/FileSystem/ModuleResources.cpp, Source/StdAfx.h
Noticed a bunch of ancient TODO comments that have probably been forgotten. Using this macro, this comments will appear in the compilation output, which will hopefully force to either address them or realize that they are done.
=> feat: add an AXO_TODO macro so TODO comments don't just get forgotten

Game/Assets/Scenes/BixPrefab.axolotl, Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl, Game/Assets/Scenes/GameplayFullTrial_Without_enemies.axolotl, Game/Assets/Scenes/NewDronePrefab.axolotl, Game/Scripts/EntityDetection.cpp, Game/Scripts/EntityDetection.h, Game/Scripts/JumpFinisherArea.cpp, Game/Scripts/MeleeHeavyAttackBehaviourScript.cpp
--Affected objects--
From Bix:
- `Bix Force Area`
- `Allura Force Area`
- `EnemyDetection`
From the drones:
- `ExplosionArea`
These objects' rigidbodies were set to kinematic and they changed from `rigidBody->SetPositionTarget()` to `rigidBody->UpdateRigidbody()` to update their movement at the same time the parent (Bix) moves. It was stated in today's meeting that this is the preferred way to move objects along with their parents.
Also, the scenes that had those objects (the newest Bix prefab or the newest drone prefab) were updated to match this change.
=> fix: from kp to update rigidbodies

Source/DataModels/Camera/CameraGameObject.cpp, Source/DataModels/Camera/CameraGameObject.h, Source/DataModels/Components/ComponentCamera.cpp, Source/DataModels/Components/ComponentCamera.h, Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentCamera.cpp, Source/Modules/ModuleCamera.cpp, Source/Modules/ModuleCamera.h, Source/Modules/ModuleRender.cpp, Source/Modules/ModuleRender.h
- Fixed the Frustum position and orientation. Now you can move scene Camera objects and Frustum gets updated.
- You can select the frustum to use and cull the objects outside it.
- The frustum selected to use is also drawn if you check it.
- Only one frustum can be selected. If none of them are checked, the Engine Camera frustum will be the one selected.
=> feat: Debug Camera Frustum utilities

Source/Auxiliar/SceneLoader.cpp, Source/Auxiliar/SceneLoader.h, Source/DataModels/Components/ComponentScript.cpp, Source/DataModels/Components/UI/ComponentSlider.cpp, Source/Modules/ModuleScene.cpp, Source/Modules/ModuleScene.h
`ModuleScene::HasNewUID` wasn't updated with the changes to how we load scenes, which resulted in us checking a map that was always empty. Moved that functionality to a helper function inside `SceneLoader`.
=> fix: scene importing works again

Source/DataModels/GameObject/GameObject.inl
As requested, forgetting to add an include of the corresponding Component gives a more descriptive compilation error when invoking method templates in GameObject.inl
Example:
=> feat[GameObject.inl]: better compilation errors if missing includes

Source/DataModels/Windows/EditorWindows/WindowInspector.cpp, Source/DataModels/Windows/EditorWindows/WindowScene.cpp, Source/Scheduler.cpp
Try to prevent sensitive methods when the scene is loading.
=> fix: add more protection when scene is loading

Game/Scripts/RangedFastAttackBehaviourScript.cpp, Source/DataModels/Components/ComponentScript.cpp
Just realized I forgot to add that. Also remove unnecessary addition to scripts; SetContainer will be called together with SetScript, so no need for scripts to call it explicitly.
=> fix: call SetContainer in copy constructor

Game/Assets/Scenes/shadow_testing.axolotl, README.md, Source/DataModels/Components/ComponentDirLight.cpp, Source/DataModels/Components/ComponentLine.cpp, Source/DataModels/PostProcess/SSAO.cpp, Source/DataModels/Program/Program.cpp, Source/DataModels/Program/Program.h, Source/DataModels/Render/Shadows.cpp, Source/DataModels/Render/Shadows.h, Source/DataModels/Scene/Scene.cpp, Source/Engine.vcxproj, Source/Engine.vcxproj.filters, Source/Modules/ModuleInput.cpp, Source/Modules/ModuleProgram.cpp, Source/Modules/ModuleProgram.h, Source/Modules/ModuleRender.cpp, Source/Modules/ModuleRender.h, Source/Shaders/Common/Structs/cascade_light_matrices.glsl, Source/Shaders/deferred_lighting_fragment.glsl, Source/Shaders/gaussian_blur_3d_fragment.glsl, Source/Shaders/gaussian_blur_3d_geometry.glsl, Source/Shaders/render_clip_space_vertex_3d.glsl, Source/Shaders/shadow_depth_variance.glsl, Source/Shaders/shadow_map_geometry.glsl, Source/Shaders/shadow_map_vertex.glsl
Implemented cascade shadow maps in order to improve shadow resolution in large scenes.
**Use F7 in order to enable CSM debugging and see the different view frustums**
|Whitout CSM|With CSM|
|----|----|
|![SM_VSM](https://github.com/Horizons-Games/Axolotl-Engine/assets/18547655/70659b88-05af-415e-aef3-f14b708d84a4)|![CSM_withVSM](https://github.com/Horizons-Games/Axolotl-Engine/assets/18547655/ea2d8480-9c3c-4239-86ab-2c3d0f80c019)|
=> feat[SCM]: Cascade Shadow Maps

Game/Scripts/EnemyDeathScript.cpp, Game/Scripts/HealthSystem.cpp, Game/Scripts/HealthSystem.h, Game/Scripts/PlayerDeathScript.cpp
The aim of this pr is to fix two bugs related to the mesh effect, and after talking with @PaablooCH, who originally designed and developed the mesh effect, we arrived to the following conclusions:
- The first bug was that, when you defeated an enemy, sometimes they turned invisible before despawning. This could be because, once an enemy is dead, all their scripts get deactivated (including the `HealthScript` that manages the mesh effect activation and deactivation) and the `ClearEffect()` fuction was sometimes not called, so that got swapped to the `EnemyDeathActions` script, ensuring that the effect will always get cleared before dying.
- The second bug was that Bix/Allura were not displaying correctly the effect sometimes, and after seeing that this does not happen in the test scenes …
=> fix: Mesh Effect bugs

Game/Scripts/ActivationLogic.cpp, Game/Scripts/ActivationLogic.h, Game/Scripts/ElevatorCore.cpp, Game/Scripts/ElevatorCore.h
- Activation Logic has an option for taking the hacking into account.
- Elevator front doors linked with the hacking completion.
- Added a cooldown to the elevator in order to prevent infinite loop up and down.
- Elevator goes up when the player is going to face the miniboss.
- Elevator goes down when the miniboss is defeated.
For testing:
- Attach miniboss GameObject to the ElevatorCore script, and custom the cooldown and the elevator speed.
=> feat: Elevator behaviour

Source/Modules/ModuleScene.cpp, Source/Modules/ModuleScene.h
Hidden in a private function so users can't request their scene load to run in-place, which was the cause of the error and would never work.
=> fix[ModuleScene]: schedule script calls to load scene

Source/Modules/ModuleRender.cpp
Scenes that did not have skybox (such as the trial scenes) couldn't be load after the skybox pr merge, this fixes it!
=> fix: load scenes without skybox

Game/Scripts/PlayerHackingUseScript.cpp, Game/Scripts/PlayerManagerScript.cpp, Game/Scripts/PlayerManagerScript.h
Solved an issue that allowed player to enable the hacking while Allura had been spawning (allowing the player to be not paralyzed while hacking)
=> fix: Hacking while switching players

Source/Auxiliar/SceneLoader.cpp, Source/DataModels/Batch/GeometryBatch.cpp, Source/DataModels/Resources/ResourceTexture.cpp, Source/FileSystem/ModuleResources.cpp, Source/FileSystem/ModuleResources.h
Loading a scene in a separated thread caused memory leaks in textures, 'cause textures can only be created, deleted and made resident and non resident in the same thread of the opengl context.
As Carlos already said: https://discord.com/channels/1029122111832338563/1030064402684194897/1130104514372960296
**This  was the cause for black textures in the scene, due to running out of vram so it coulnd't load any more textures**
=> fix[SceneLoad]: fixed memory leak in load scene async

Source/Auxiliar/GameBuilder.cpp, Source/FileSystem/ModuleFileSystem.cpp, Source/FileSystem/ModuleFileSystem.h, Source/Modules/ModuleScene.cpp, Source/Modules/ModuleScene.h, Source/Scheduler.cpp
Couple of things fixed in this MR:
- Mutexes are now properly locked. Didn't realize that I forgot to give a name to a lock a few months back, and have been copy-pasting that mistake all over the place. Fixed that and the deadlocks that came up because of it.
- Scheduler::RunTasks stores a snapshot of the current state of the Schedulable queue. We retrieve the front of the queue as a reference `Schedulable& schedulable = ...`, but if the queue reallocates somewhere else (because ScheduleTask was called, for example), that memory can become invalid, which I'm almost positive is the cause of the original crash reported.
=> fix: proper use of mutexes + scheduler fix

Source/FileSystem/ModuleFileSystem.cpp
Now the game settings are added into the asset folder when made a build
=> chore [UI]: add settings folder into ZIP when build

Game/Scripts/SwitchPlayerManagerScript.cpp, Game/Scripts/SwitchPlayerManagerScript.h, Game/Scripts/UIGameManager.cpp, Game/Scripts/UIGameManager.h
GameOver screen now only appears when the UI health bar ends the full animation or certain time pass. With this you can proper see the death of the character.
The flow should be Bix death animation -> HealthBar goes down -> In case the HealthBar goes down is too short we have a auxiliar timer to wait a minimum time -> GameOver screen.
=> Fix: gameOver waits until health bar do the animation

Game/Scripts/ActivationLogic.cpp, Game/Scripts/ActivationLogic.h, Game/Scripts/EnemyVenomiteScript.cpp, Game/Scripts/PathBehaviourScript.cpp, Game/Scripts/PlayerMoveScript.cpp
- Now enemies have a path to the navmesh and then they patrol.
- Fix the error with the doors. When enemies try to pass the door is closed because the player is in combat mode.
- Now when an enemy is respawned we force stop patrolling in case that the enemy finishes in this state.
=> refactor: level 2 spawn from enemies

Game/Scripts/BossChargeAttackScript.cpp, Game/Scripts/CameraBossControllerScript.cpp
- Boss charge attack failed when Player was not moving. Inaccurate target point fixed.
- Avoided camera to rotate around X axis when Boss gets closer to Player.
=> fix: Boss charge attack

Source/DataModels/Components/ComponentPlanarReflection.cpp
Fix an issue when loading a scene with planar reflections.
Level 2  have more stable fps.
Removed most of the planar.
=> fix: increased planar performance

Source/DataModels/Render/Shadows.h, Source/DataModels/Windows/WindowDebug.cpp, Source/Modules/ModuleRender.h
Now we can debug graphics using the debug mode in-game (**alt + j**).
PD: commented wireframe mode 'cause it is not working
=> feat: added debugging for graphic features in game mode

Source/Shaders/gaussian_blur.glsl
For how planar reflections work, the final color must use the alpha provided by the in-texture. This shouldn't affect any other texture that uses this method, like ssao, because all the textures are created with alpha = 1, unless you clean those values.
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/15668327-3356-4c84-aeee-318db5e90dbd)  | ![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/11cde838-8499-4c2a-a5ef-450ced6958f7)  |
| ![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/feb99434-b41c-4789-94e2-cc25dea7c8af)  | ![image](https://github.com/Horizons-Games/Axolotl-Engine/assets/62140600/c82cd632-be00-4176-a84d-f25d7c88388e)  |
SSAO texture:
=> chore: adapted gaussian blur

Game/Scripts/MeshEffect.cpp
While the fade out effect was running, the "true" mesh was still reflected on the surface. Now only the fade out mesh is reflected.
=> fix: fade out with reflection
